# Generated by Django 5.2.4 on 2025-07-10 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('launch_year', models.IntegerField()),
                ('genre', models.CharField()),
                ('score', models.FloatField()),
                ('director', models.CharField(default='감독 미상')),
                ('cast', models.CharField(default='배우 미상')),
                ('running_time', models.IntegerField(default=0)),
            ],
        ),
    ]
