# Generated by Django 5.2.4 on 2025-07-10 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_review_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='genre',
            field=models.CharField(choices=[('action', 'action'), ('SF', 'SF'), ('drama', 'drama'), ('comedy', 'comedy'), ('romance', 'romance'), ('thriller', 'thriller')], max_length=100),
        ),
    ]
