# Generated by Django 5.2.4 on 2025-07-10 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_review_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='genre',
            field=models.CharField(choices=[('Action', 'Action'), ('SF', 'SF'), ('Drama', 'Drama'), ('Comedy', 'Comedy'), ('Romance', 'Romance'), ('Thriller', 'Thriller')], max_length=100),
        ),
    ]
